server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.62.89:3306/stu_analysis_system?serverTimezone=UTC
    username: root
    password: 256817
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com
    # 发送者的邮箱账号
    username: 2032340558@qq.com
    # 邮箱密码授权码
    password: suajvurtgkssddjj
    default-encoding: utf-8
    properties:
      mail:
#        debug: true
        smtp:
          ssl:
            enable: true
            trust: smtp.qq.com
          auth: true
          starttls:
            enable: true
            required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    port: 465
    protocol: smtp


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/xml/*Mapper.xml